services:
  # Backend Node/Express Web Service
  - type: web
    name: nexstack-pos-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://kit27ad17:Aidsdr-003@cluster0.nl8lf1t.mongodb.net/nineteen06?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: nexstack_super_secret_jwt_access_key_2026
      - key: JWT_REFRESH_SECRET
        value: nexstack_super_secret_jwt_refresh_key_2026
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: SUPABASE_URL
        value: https://saxscmsnjyctqqwxoqfa.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheHNjbXNuanljdHFxd3hvcWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxMjAzMzEsImV4cCI6MjEwMzY5NjMzMX0.RQwZggDY-99XmvK15NNxsgEWuqhfasjpb2dmAP5Olhs
      - key: SUPABASE_SECRET_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheHNjbXNuanljdHFxd3hvcWZhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODEyMDMzMSwiZXhwIjoyMTAzNjk2MzMxfQ.IbuuoyeDGMmiVxWuoMGhiyzpLXGYeadrTKQObxyzwII

  # Frontend Static Site
  - type: web
    name: nexstack-pos-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nexstack-pos-backend
          property: host
